---
- name: Installing necessary packages
  apt:
    name="{{ item }}"
    state=latest
    update_cache=yes
  with_items:
    - haproxy
    - vim
    - git
    - ntp
- name: Enabling haproxy service in /etc/default/haproxy
  lineinfile:
    path: /etc/default/haproxy
    regexp: 'ENABLED=0'
    line: 'ENABLED=1'
    backrefs: yes

- name: Configuring haproxy cfg from template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

